# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43ommon.proto\"\x18\n\x07Nothing\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\"\x1d\n\x07Success\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\"6\n\x07NameDTO\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0e\n\x06middle\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\t\"\'\n\x07TimeDTO\x12\x0c\n\x04hour\x18\x01 \x01(\r\x12\x0e\n\x06minute\x18\x02 \x01(\r\"K\n\x07\x44\x61teDTO\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\x12\x16\n\x04time\x18\x04 \x01(\x0b\x32\x08.TimeDTO\"_\n\x08ShiftDTO\x12\x17\n\x05start\x18\x01 \x01(\x0b\x32\x08.DateDTO\x12\x17\n\x05other\x18\x02 \x01(\x0b\x32\x08.DateDTO\x12\x10\n\x08\x64uration\x18\x03 \x01(\x04\x12\x0f\n\x07room_id\x18\x04 \x01(\r\"\x1e\n\x0bRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\r2_\n\x06\x43ommon\x12\x1c\n\x06update\x12\x08.Nothing\x1a\x08.Nothing\x12\x1b\n\x05print\x12\x08.Nothing\x1a\x08.Nothing\x12\x1a\n\x04ping\x12\x08.Nothing\x1a\x08.Nothingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTHING']._serialized_start=16
  _globals['_NOTHING']._serialized_end=40
  _globals['_SUCCESS']._serialized_start=42
  _globals['_SUCCESS']._serialized_end=71
  _globals['_NAMEDTO']._serialized_start=73
  _globals['_NAMEDTO']._serialized_end=127
  _globals['_TIMEDTO']._serialized_start=129
  _globals['_TIMEDTO']._serialized_end=168
  _globals['_DATEDTO']._serialized_start=170
  _globals['_DATEDTO']._serialized_end=245
  _globals['_SHIFTDTO']._serialized_start=247
  _globals['_SHIFTDTO']._serialized_end=342
  _globals['_ROOMREQUEST']._serialized_start=344
  _globals['_ROOMREQUEST']._serialized_end=374
  _globals['_COMMON']._serialized_start=376
  _globals['_COMMON']._serialized_end=471
# @@protoc_insertion_point(module_scope)
