# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Common_pb2 as Common__pb2
import PatientManagement_pb2 as PatientManagement__pb2


class PatientManagementStub(object):
    """Each one of these must be accessible by the front end
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdmitPatient = channel.unary_unary(
                '/PatientManagement/AdmitPatient',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.DischargePatient = channel.unary_unary(
                '/PatientManagement/DischargePatient',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.TransferPatient = channel.unary_unary(
                '/PatientManagement/TransferPatient',
                request_serializer=PatientManagement__pb2.PatientTransfer.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.QuarantinePatient = channel.unary_unary(
                '/PatientManagement/QuarantinePatient',
                request_serializer=PatientManagement__pb2.PatientQuarantine.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.LiftPatientQuarantine = channel.unary_unary(
                '/PatientManagement/LiftPatientQuarantine',
                request_serializer=PatientManagement__pb2.PatientQuarantine.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.GetPatientInformation = channel.unary_unary(
                '/PatientManagement/GetPatientInformation',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                _registered_method=True)
        self.UpdatePatientInformation = channel.unary_unary(
                '/PatientManagement/UpdatePatientInformation',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.GetPatientsInRoom = channel.unary_unary(
                '/PatientManagement/GetPatientsInRoom',
                request_serializer=Common__pb2.RoomRequest.SerializeToString,
                response_deserializer=PatientManagement__pb2.PatientList.FromString,
                _registered_method=True)


class PatientManagementServicer(object):
    """Each one of these must be accessible by the front end
    """

    def AdmitPatient(self, request, context):
        """Patient movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DischargePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuarantinePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiftPatientQuarantine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientInformation(self, request, context):
        """Patient information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatientInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientsInRoom(self, request, context):
        """This call is not accessible to the front end 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdmitPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.AdmitPatient,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'DischargePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.DischargePatient,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'TransferPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferPatient,
                    request_deserializer=PatientManagement__pb2.PatientTransfer.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'QuarantinePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.QuarantinePatient,
                    request_deserializer=PatientManagement__pb2.PatientQuarantine.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'LiftPatientQuarantine': grpc.unary_unary_rpc_method_handler(
                    servicer.LiftPatientQuarantine,
                    request_deserializer=PatientManagement__pb2.PatientQuarantine.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'GetPatientInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientInformation,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
            ),
            'UpdatePatientInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatientInformation,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'GetPatientsInRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientsInRoom,
                    request_deserializer=Common__pb2.RoomRequest.FromString,
                    response_serializer=PatientManagement__pb2.PatientList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PatientManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PatientManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientManagement(object):
    """Each one of these must be accessible by the front end
    """

    @staticmethod
    def AdmitPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/AdmitPatient',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DischargePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/DischargePatient',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/TransferPatient',
            PatientManagement__pb2.PatientTransfer.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuarantinePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/QuarantinePatient',
            PatientManagement__pb2.PatientQuarantine.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiftPatientQuarantine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/LiftPatientQuarantine',
            PatientManagement__pb2.PatientQuarantine.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/GetPatientInformation',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            PatientManagement__pb2.PatientDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePatientInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/UpdatePatientInformation',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientsInRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PatientManagement/GetPatientsInRoom',
            Common__pb2.RoomRequest.SerializeToString,
            PatientManagement__pb2.PatientList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
