# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PatientManagement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PatientManagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PatientManagement.proto\x1a\x0c\x43ommon.proto\"\xac\x01\n\nPatientDTO\x12\x1e\n\x0cpatient_name\x18\x01 \x01(\x0b\x32\x08.NameDTO\x12\x12\n\npatient_id\x18\x02 \x01(\x04\x12\x13\n\x0bpatient_sex\x18\x03 \x01(\t\x12\x14\n\x0cpatient_cond\x18\x04 \x01(\t\x12\x14\n\x0cpatient_room\x18\x05 \x01(\r\x12\x11\n\troom_type\x18\x06 \x01(\t\x12\x16\n\x0eis_quarantined\x18\x07 \x01(\x08\"z\n\x0fPatientTransfer\x12\x12\n\npatient_id\x18\x01 \x01(\x04\x12\x13\n\x0bold_room_id\x18\x02 \x01(\r\x12\x13\n\x0bnew_room_id\x18\x03 \x01(\r\x12\x11\n\troom_type\x18\x04 \x01(\t\x12\x16\n\x0eis_quarantined\x18\x05 \x01(\x08\"@\n\x11PatientQuarantine\x12\x12\n\npatient_id\x18\x01 \x01(\x04\x12\x17\n\x0fquarantine_room\x18\x02 \x01(\x08\",\n\x0bPatientList\x12\x1d\n\x08patients\x18\x01 \x03(\x0b\x32\x0b.PatientDTO2\x95\x03\n\x11PatientManagement\x12%\n\x0c\x41\x64mitPatient\x12\x0b.PatientDTO\x1a\x08.Success\x12)\n\x10\x44ischargePatient\x12\x0b.PatientDTO\x1a\x08.Success\x12-\n\x0fTransferPatient\x12\x10.PatientTransfer\x1a\x08.Success\x12\x31\n\x11QuarantinePatient\x12\x12.PatientQuarantine\x1a\x08.Success\x12\x35\n\x15LiftPatientQuarantine\x12\x12.PatientQuarantine\x1a\x08.Success\x12\x31\n\x15GetPatientInformation\x12\x0b.PatientDTO\x1a\x0b.PatientDTO\x12\x31\n\x18UpdatePatientInformation\x12\x0b.PatientDTO\x1a\x08.Success\x12/\n\x11GetPatientsInRoom\x12\x0c.RoomRequest\x1a\x0c.PatientListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PatientManagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENTDTO']._serialized_start=42
  _globals['_PATIENTDTO']._serialized_end=214
  _globals['_PATIENTTRANSFER']._serialized_start=216
  _globals['_PATIENTTRANSFER']._serialized_end=338
  _globals['_PATIENTQUARANTINE']._serialized_start=340
  _globals['_PATIENTQUARANTINE']._serialized_end=404
  _globals['_PATIENTLIST']._serialized_start=406
  _globals['_PATIENTLIST']._serialized_end=450
  _globals['_PATIENTMANAGEMENT']._serialized_start=453
  _globals['_PATIENTMANAGEMENT']._serialized_end=858
# @@protoc_insertion_point(module_scope)
