# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResourceManagement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ResourceManagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ResourceManagement.proto\x1a\x0c\x43ommon.proto\"b\n\x0bResourceDTO\x12\x13\n\x0bresource_id\x18\x01 \x01(\x04\x12\x0f\n\x07room_id\x18\x02 \x01(\r\x12\x15\n\rresource_type\x18\x03 \x01(\t\x12\x16\n\x0eresource_stock\x18\x04 \x01(\r\"I\n\rResourceShift\x12\x1e\n\x08resource\x18\x01 \x01(\x0b\x32\x0c.ResourceDTO\x12\x18\n\x05shift\x18\x02 \x01(\x0b\x32\t.ShiftDTO\"O\n\x0bStockUpdate\x12\x13\n\x0bresource_id\x18\x01 \x01(\x04\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x14\n\x0cstock_amount\x18\x03 \x01(\r\"/\n\x0cResourceList\x12\x1f\n\tresources\x18\x01 \x03(\x0b\x32\x0c.ResourceDTO\"1\n\x10ResourceSchedule\x12\x1d\n\x05\x64\x61tes\x18\x01 \x03(\x0b\x32\x0e.ResourceShift2\xf9\x05\n\x12ResourceManagement\x12*\n\x10RegisterResource\x12\x0c.ResourceDTO\x1a\x08.Success\x12,\n\x12\x44\x65registerResource\x12\x0c.ResourceDTO\x1a\x08.Success\x12,\n\x12SendForMaintenance\x12\x0c.ResourceDTO\x1a\x08.Success\x12)\n\rAddToSchedule\x12\x0e.ResourceShift\x1a\x08.Success\x12.\n\x12RemoveFromSchedule\x12\x0e.ResourceShift\x1a\x08.Success\x12\x30\n\x16RemoveResourceFromRoom\x12\x0c.ResourceDTO\x1a\x08.Success\x12*\n\x0e\x43hangeSchedule\x12\x0e.ResourceShift\x1a\x08.Success\x12\x34\n\x11SeeTodaysSchedule\x12\x0c.ResourceDTO\x1a\x11.ResourceSchedule\x12\x37\n\x14SeeTomorrowsSchedule\x12\x0c.ResourceDTO\x1a\x11.ResourceSchedule\x12\x35\n\x10SeeScheduleRange\x12\x0e.ResourceShift\x1a\x11.ResourceSchedule\x12\"\n\x08\x41\x64\x64Stock\x12\x0c.StockUpdate\x1a\x08.Success\x12%\n\x0bRemoveStock\x12\x0c.StockUpdate\x1a\x08.Success\x12\"\n\x08UseStock\x12\x0c.StockUpdate\x1a\x08.Success\x12$\n\nEmptyStock\x12\x0c.StockUpdate\x1a\x08.Success\x12\x34\n\x16GetResourceInformation\x12\x0c.ResourceDTO\x1a\x0c.ResourceDTO\x12\x31\n\x12GetResourcesInRoom\x12\x0c.RoomRequest\x1a\r.ResourceListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResourceManagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEDTO']._serialized_start=42
  _globals['_RESOURCEDTO']._serialized_end=140
  _globals['_RESOURCESHIFT']._serialized_start=142
  _globals['_RESOURCESHIFT']._serialized_end=215
  _globals['_STOCKUPDATE']._serialized_start=217
  _globals['_STOCKUPDATE']._serialized_end=296
  _globals['_RESOURCELIST']._serialized_start=298
  _globals['_RESOURCELIST']._serialized_end=345
  _globals['_RESOURCESCHEDULE']._serialized_start=347
  _globals['_RESOURCESCHEDULE']._serialized_end=396
  _globals['_RESOURCEMANAGEMENT']._serialized_start=399
  _globals['_RESOURCEMANAGEMENT']._serialized_end=1160
# @@protoc_insertion_point(module_scope)
