# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Common_pb2 as Common__pb2
import ResourceManagement_pb2 as ResourceManagement__pb2


class ResourceManagementStub(object):
    """Each one of these must be accessible by the front end
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterResource = channel.unary_unary(
                '/ResourceManagement/RegisterResource',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.DeregisterResource = channel.unary_unary(
                '/ResourceManagement/DeregisterResource',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.SendForMaintenance = channel.unary_unary(
                '/ResourceManagement/SendForMaintenance',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.AddToSchedule = channel.unary_unary(
                '/ResourceManagement/AddToSchedule',
                request_serializer=ResourceManagement__pb2.ResourceShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RemoveFromSchedule = channel.unary_unary(
                '/ResourceManagement/RemoveFromSchedule',
                request_serializer=ResourceManagement__pb2.ResourceShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RemoveResourceFromRoom = channel.unary_unary(
                '/ResourceManagement/RemoveResourceFromRoom',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.ChangeSchedule = channel.unary_unary(
                '/ResourceManagement/ChangeSchedule',
                request_serializer=ResourceManagement__pb2.ResourceShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.SeeTodaysSchedule = channel.unary_unary(
                '/ResourceManagement/SeeTodaysSchedule',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=ResourceManagement__pb2.ResourceSchedule.FromString,
                _registered_method=True)
        self.SeeTomorrowsSchedule = channel.unary_unary(
                '/ResourceManagement/SeeTomorrowsSchedule',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=ResourceManagement__pb2.ResourceSchedule.FromString,
                _registered_method=True)
        self.SeeScheduleRange = channel.unary_unary(
                '/ResourceManagement/SeeScheduleRange',
                request_serializer=ResourceManagement__pb2.ResourceShift.SerializeToString,
                response_deserializer=ResourceManagement__pb2.ResourceSchedule.FromString,
                _registered_method=True)
        self.AddStock = channel.unary_unary(
                '/ResourceManagement/AddStock',
                request_serializer=ResourceManagement__pb2.StockUpdate.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RemoveStock = channel.unary_unary(
                '/ResourceManagement/RemoveStock',
                request_serializer=ResourceManagement__pb2.StockUpdate.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.UseStock = channel.unary_unary(
                '/ResourceManagement/UseStock',
                request_serializer=ResourceManagement__pb2.StockUpdate.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.EmptyStock = channel.unary_unary(
                '/ResourceManagement/EmptyStock',
                request_serializer=ResourceManagement__pb2.StockUpdate.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.GetResourceInformation = channel.unary_unary(
                '/ResourceManagement/GetResourceInformation',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                _registered_method=True)
        self.GetResourcesInRoom = channel.unary_unary(
                '/ResourceManagement/GetResourcesInRoom',
                request_serializer=Common__pb2.RoomRequest.SerializeToString,
                response_deserializer=ResourceManagement__pb2.ResourceList.FromString,
                _registered_method=True)


class ResourceManagementServicer(object):
    """Each one of these must be accessible by the front end
    """

    def RegisterResource(self, request, context):
        """Machine Resource Movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendForMaintenance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToSchedule(self, request, context):
        """Machine Resource Scheduling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveResourceFromRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeTodaysSchedule(self, request, context):
        """Schedule viewing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeTomorrowsSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeScheduleRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStock(self, request, context):
        """Consumable Resource Updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmptyStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceInformation(self, request, context):
        """Resource Information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourcesInRoom(self, request, context):
        """This call is not accessible to the front end 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterResource': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterResource,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'DeregisterResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterResource,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'SendForMaintenance': grpc.unary_unary_rpc_method_handler(
                    servicer.SendForMaintenance,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'AddToSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToSchedule,
                    request_deserializer=ResourceManagement__pb2.ResourceShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RemoveFromSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromSchedule,
                    request_deserializer=ResourceManagement__pb2.ResourceShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RemoveResourceFromRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveResourceFromRoom,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'ChangeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeSchedule,
                    request_deserializer=ResourceManagement__pb2.ResourceShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'SeeTodaysSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeTodaysSchedule,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=ResourceManagement__pb2.ResourceSchedule.SerializeToString,
            ),
            'SeeTomorrowsSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeTomorrowsSchedule,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=ResourceManagement__pb2.ResourceSchedule.SerializeToString,
            ),
            'SeeScheduleRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeScheduleRange,
                    request_deserializer=ResourceManagement__pb2.ResourceShift.FromString,
                    response_serializer=ResourceManagement__pb2.ResourceSchedule.SerializeToString,
            ),
            'AddStock': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStock,
                    request_deserializer=ResourceManagement__pb2.StockUpdate.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RemoveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStock,
                    request_deserializer=ResourceManagement__pb2.StockUpdate.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'UseStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UseStock,
                    request_deserializer=ResourceManagement__pb2.StockUpdate.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'EmptyStock': grpc.unary_unary_rpc_method_handler(
                    servicer.EmptyStock,
                    request_deserializer=ResourceManagement__pb2.StockUpdate.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'GetResourceInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceInformation,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
            ),
            'GetResourcesInRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourcesInRoom,
                    request_deserializer=Common__pb2.RoomRequest.FromString,
                    response_serializer=ResourceManagement__pb2.ResourceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResourceManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ResourceManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResourceManagement(object):
    """Each one of these must be accessible by the front end
    """

    @staticmethod
    def RegisterResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/RegisterResource',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/DeregisterResource',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendForMaintenance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/SendForMaintenance',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/AddToSchedule',
            ResourceManagement__pb2.ResourceShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/RemoveFromSchedule',
            ResourceManagement__pb2.ResourceShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveResourceFromRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/RemoveResourceFromRoom',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/ChangeSchedule',
            ResourceManagement__pb2.ResourceShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeTodaysSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/SeeTodaysSchedule',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            ResourceManagement__pb2.ResourceSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeTomorrowsSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/SeeTomorrowsSchedule',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            ResourceManagement__pb2.ResourceSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeScheduleRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/SeeScheduleRange',
            ResourceManagement__pb2.ResourceShift.SerializeToString,
            ResourceManagement__pb2.ResourceSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/AddStock',
            ResourceManagement__pb2.StockUpdate.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/RemoveStock',
            ResourceManagement__pb2.StockUpdate.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UseStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/UseStock',
            ResourceManagement__pb2.StockUpdate.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmptyStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/EmptyStock',
            ResourceManagement__pb2.StockUpdate.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/GetResourceInformation',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            ResourceManagement__pb2.ResourceDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourcesInRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ResourceManagement/GetResourcesInRoom',
            Common__pb2.RoomRequest.SerializeToString,
            ResourceManagement__pb2.ResourceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
