# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Common_pb2 as Common__pb2
import PatientManagement_pb2 as PatientManagement__pb2
import ResourceManagement_pb2 as ResourceManagement__pb2
import RoomManagement_pb2 as RoomManagement__pb2
import StaffManagement_pb2 as StaffManagement__pb2


class RoomManagementStub(object):
    """These calls will not be accessible to the front end 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdmitPatient = channel.unary_unary(
                '/RoomManagement/AdmitPatient',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=Common__pb2.RoomRequest.FromString,
                _registered_method=True)
        self.DischargePatient = channel.unary_unary(
                '/RoomManagement/DischargePatient',
                request_serializer=PatientManagement__pb2.PatientDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.TransferPatient = channel.unary_unary(
                '/RoomManagement/TransferPatient',
                request_serializer=PatientManagement__pb2.PatientTransfer.SerializeToString,
                response_deserializer=Common__pb2.RoomRequest.FromString,
                _registered_method=True)
        self.QuarantinePatient = channel.unary_unary(
                '/RoomManagement/QuarantinePatient',
                request_serializer=PatientManagement__pb2.PatientQuarantine.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.LiftPatientQuarantine = channel.unary_unary(
                '/RoomManagement/LiftPatientQuarantine',
                request_serializer=PatientManagement__pb2.PatientQuarantine.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RetrieveResource = channel.unary_unary(
                '/RoomManagement/RetrieveResource',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.ReleaseResource = channel.unary_unary(
                '/RoomManagement/ReleaseResource',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.TransferResource = channel.unary_unary(
                '/RoomManagement/TransferResource',
                request_serializer=ResourceManagement__pb2.ResourceDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RetrieveStaff = channel.unary_unary(
                '/RoomManagement/RetrieveStaff',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.ReleaseStaff = channel.unary_unary(
                '/RoomManagement/ReleaseStaff',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.TransferStaff = channel.unary_unary(
                '/RoomManagement/TransferStaff',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.QuarantineRoom = channel.unary_unary(
                '/RoomManagement/QuarantineRoom',
                request_serializer=RoomManagement__pb2.RoomQuarantine.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.GetRoomInformation = channel.unary_unary(
                '/RoomManagement/GetRoomInformation',
                request_serializer=RoomManagement__pb2.RoomDTO.SerializeToString,
                response_deserializer=RoomManagement__pb2.RoomInformation.FromString,
                _registered_method=True)


class RoomManagementServicer(object):
    """These calls will not be accessible to the front end 
    """

    def AdmitPatient(self, request, context):
        """Patient Management Requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DischargePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuarantinePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiftPatientQuarantine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveResource(self, request, context):
        """Resource Management Requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveStaff(self, request, context):
        """Staff Management Requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseStaff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferStaff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuarantineRoom(self, request, context):
        """These calls need to be accessable to the front end 

        Front End Requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomInformation(self, request, context):
        """Displays all the people and resources in a room
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdmitPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.AdmitPatient,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=Common__pb2.RoomRequest.SerializeToString,
            ),
            'DischargePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.DischargePatient,
                    request_deserializer=PatientManagement__pb2.PatientDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'TransferPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferPatient,
                    request_deserializer=PatientManagement__pb2.PatientTransfer.FromString,
                    response_serializer=Common__pb2.RoomRequest.SerializeToString,
            ),
            'QuarantinePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.QuarantinePatient,
                    request_deserializer=PatientManagement__pb2.PatientQuarantine.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'LiftPatientQuarantine': grpc.unary_unary_rpc_method_handler(
                    servicer.LiftPatientQuarantine,
                    request_deserializer=PatientManagement__pb2.PatientQuarantine.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RetrieveResource': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveResource,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'ReleaseResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseResource,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'TransferResource': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferResource,
                    request_deserializer=ResourceManagement__pb2.ResourceDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RetrieveStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveStaff,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'ReleaseStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseStaff,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'TransferStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferStaff,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'QuarantineRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.QuarantineRoom,
                    request_deserializer=RoomManagement__pb2.RoomQuarantine.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'GetRoomInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomInformation,
                    request_deserializer=RoomManagement__pb2.RoomDTO.FromString,
                    response_serializer=RoomManagement__pb2.RoomInformation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoomManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RoomManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomManagement(object):
    """These calls will not be accessible to the front end 
    """

    @staticmethod
    def AdmitPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/AdmitPatient',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            Common__pb2.RoomRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DischargePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/DischargePatient',
            PatientManagement__pb2.PatientDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/TransferPatient',
            PatientManagement__pb2.PatientTransfer.SerializeToString,
            Common__pb2.RoomRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuarantinePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/QuarantinePatient',
            PatientManagement__pb2.PatientQuarantine.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiftPatientQuarantine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/LiftPatientQuarantine',
            PatientManagement__pb2.PatientQuarantine.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/RetrieveResource',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/ReleaseResource',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/TransferResource',
            ResourceManagement__pb2.ResourceDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/RetrieveStaff',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/ReleaseStaff',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/TransferStaff',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuarantineRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/QuarantineRoom',
            RoomManagement__pb2.RoomQuarantine.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoomInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoomManagement/GetRoomInformation',
            RoomManagement__pb2.RoomDTO.SerializeToString,
            RoomManagement__pb2.RoomInformation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
