# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoomManagement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RoomManagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import PatientManagement_pb2 as PatientManagement__pb2
import ResourceManagement_pb2 as ResourceManagement__pb2
import StaffManagement_pb2 as StaffManagement__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RoomManagement.proto\x1a\x0c\x43ommon.proto\x1a\x17PatientManagement.proto\x1a\x18ResourceManagement.proto\x1a\x15StaffManagement.proto\"s\n\x07RoomDTO\x12\x11\n\troom_type\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\r\x12\x15\n\rroom_capacity\x18\x03 \x01(\r\x12\x18\n\x10\x63urrent_capacity\x18\x04 \x01(\r\x12\x13\n\x0bquarantined\x18\x05 \x01(\x08\"K\n\x0eRoomQuarantine\x12\x0f\n\x07room_id\x18\x01 \x01(\r\x12\x12\n\nquarantine\x18\x02 \x01(\x08\x12\x14\n\x0cmove_patient\x18\x03 \x01(\x08\"\xb4\x01\n\x0fRoomInformation\x12\"\n\x10room_information\x18\x01 \x01(\x0b\x32\x08.RoomDTO\x12)\n\x13patient_information\x18\x02 \x01(\x0b\x32\x0c.PatientList\x12+\n\x14resource_information\x18\x03 \x01(\x0b\x32\r.ResourceList\x12%\n\x11staff_information\x18\x04 \x01(\x0b\x32\n.StaffList2\xd6\x04\n\x0eRoomManagement\x12)\n\x0c\x41\x64mitPatient\x12\x0b.PatientDTO\x1a\x0c.RoomRequest\x12)\n\x10\x44ischargePatient\x12\x0b.PatientDTO\x1a\x08.Success\x12\x31\n\x0fTransferPatient\x12\x10.PatientTransfer\x1a\x0c.RoomRequest\x12\x31\n\x11QuarantinePatient\x12\x12.PatientQuarantine\x1a\x08.Success\x12\x35\n\x15LiftPatientQuarantine\x12\x12.PatientQuarantine\x1a\x08.Success\x12*\n\x10RetrieveResource\x12\x0c.ResourceDTO\x1a\x08.Success\x12)\n\x0fReleaseResource\x12\x0c.ResourceDTO\x1a\x08.Success\x12*\n\x10TransferResource\x12\x0c.ResourceDTO\x1a\x08.Success\x12$\n\rRetrieveStaff\x12\t.StaffDTO\x1a\x08.Success\x12#\n\x0cReleaseStaff\x12\t.StaffDTO\x1a\x08.Success\x12$\n\rTransferStaff\x12\t.StaffDTO\x1a\x08.Success\x12+\n\x0eQuarantineRoom\x12\x0f.RoomQuarantine\x1a\x08.Success\x12\x30\n\x12GetRoomInformation\x12\x08.RoomDTO\x1a\x10.RoomInformationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RoomManagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMDTO']._serialized_start=112
  _globals['_ROOMDTO']._serialized_end=227
  _globals['_ROOMQUARANTINE']._serialized_start=229
  _globals['_ROOMQUARANTINE']._serialized_end=304
  _globals['_ROOMINFORMATION']._serialized_start=307
  _globals['_ROOMINFORMATION']._serialized_end=487
  _globals['_ROOMMANAGEMENT']._serialized_start=490
  _globals['_ROOMMANAGEMENT']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
