# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Common_pb2 as Common__pb2
import StaffManagement_pb2 as StaffManagement__pb2


class StaffManagementStub(object):
    """Each one of these must be accessible by the front end
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStaff = channel.unary_unary(
                '/StaffManagement/AddStaff',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RemoveStaff = channel.unary_unary(
                '/StaffManagement/RemoveStaff',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.ChangePosition = channel.unary_unary(
                '/StaffManagement/ChangePosition',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.ChangeClearance = channel.unary_unary(
                '/StaffManagement/ChangeClearance',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.UpdateStaffInformation = channel.unary_unary(
                '/StaffManagement/UpdateStaffInformation',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.AddShift = channel.unary_unary(
                '/StaffManagement/AddShift',
                request_serializer=StaffManagement__pb2.StaffShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.RemoveShift = channel.unary_unary(
                '/StaffManagement/RemoveShift',
                request_serializer=StaffManagement__pb2.StaffShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.TransferShift = channel.unary_unary(
                '/StaffManagement/TransferShift',
                request_serializer=StaffManagement__pb2.StaffShift.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.BookTimeOff = channel.unary_unary(
                '/StaffManagement/BookTimeOff',
                request_serializer=StaffManagement__pb2.TimeOff.SerializeToString,
                response_deserializer=Common__pb2.Success.FromString,
                _registered_method=True)
        self.SeeStaffInformation = channel.unary_unary(
                '/StaffManagement/SeeStaffInformation',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                _registered_method=True)
        self.SeeTodaysSchedule = channel.unary_unary(
                '/StaffManagement/SeeTodaysSchedule',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=StaffManagement__pb2.StaffSchedule.FromString,
                _registered_method=True)
        self.SeeTomorrowsSchedule = channel.unary_unary(
                '/StaffManagement/SeeTomorrowsSchedule',
                request_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
                response_deserializer=StaffManagement__pb2.StaffSchedule.FromString,
                _registered_method=True)
        self.SeeScheduleRange = channel.unary_unary(
                '/StaffManagement/SeeScheduleRange',
                request_serializer=StaffManagement__pb2.StaffShift.SerializeToString,
                response_deserializer=StaffManagement__pb2.StaffSchedule.FromString,
                _registered_method=True)
        self.GetStaffInRoom = channel.unary_unary(
                '/StaffManagement/GetStaffInRoom',
                request_serializer=Common__pb2.RoomRequest.SerializeToString,
                response_deserializer=StaffManagement__pb2.StaffList.FromString,
                _registered_method=True)


class StaffManagementServicer(object):
    """Each one of these must be accessible by the front end
    """

    def AddStaff(self, request, context):
        """Staff Movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStaff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePosition(self, request, context):
        """Staff Information Updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeClearance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStaffInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddShift(self, request, context):
        """Staff Scheduling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveShift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferShift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookTimeOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeStaffInformation(self, request, context):
        """Staff Information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeTodaysSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeTomorrowsSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeeScheduleRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStaffInRoom(self, request, context):
        """This call is not accessible to the front end 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StaffManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStaff,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RemoveStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStaff,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'ChangePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePosition,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'ChangeClearance': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeClearance,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'UpdateStaffInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStaffInformation,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'AddShift': grpc.unary_unary_rpc_method_handler(
                    servicer.AddShift,
                    request_deserializer=StaffManagement__pb2.StaffShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'RemoveShift': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveShift,
                    request_deserializer=StaffManagement__pb2.StaffShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'TransferShift': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferShift,
                    request_deserializer=StaffManagement__pb2.StaffShift.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'BookTimeOff': grpc.unary_unary_rpc_method_handler(
                    servicer.BookTimeOff,
                    request_deserializer=StaffManagement__pb2.TimeOff.FromString,
                    response_serializer=Common__pb2.Success.SerializeToString,
            ),
            'SeeStaffInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeStaffInformation,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=StaffManagement__pb2.StaffDTO.SerializeToString,
            ),
            'SeeTodaysSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeTodaysSchedule,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=StaffManagement__pb2.StaffSchedule.SerializeToString,
            ),
            'SeeTomorrowsSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeTomorrowsSchedule,
                    request_deserializer=StaffManagement__pb2.StaffDTO.FromString,
                    response_serializer=StaffManagement__pb2.StaffSchedule.SerializeToString,
            ),
            'SeeScheduleRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SeeScheduleRange,
                    request_deserializer=StaffManagement__pb2.StaffShift.FromString,
                    response_serializer=StaffManagement__pb2.StaffSchedule.SerializeToString,
            ),
            'GetStaffInRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStaffInRoom,
                    request_deserializer=Common__pb2.RoomRequest.FromString,
                    response_serializer=StaffManagement__pb2.StaffList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StaffManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StaffManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StaffManagement(object):
    """Each one of these must be accessible by the front end
    """

    @staticmethod
    def AddStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/AddStaff',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/RemoveStaff',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/ChangePosition',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeClearance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/ChangeClearance',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStaffInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/UpdateStaffInformation',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddShift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/AddShift',
            StaffManagement__pb2.StaffShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveShift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/RemoveShift',
            StaffManagement__pb2.StaffShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferShift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/TransferShift',
            StaffManagement__pb2.StaffShift.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookTimeOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/BookTimeOff',
            StaffManagement__pb2.TimeOff.SerializeToString,
            Common__pb2.Success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeStaffInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/SeeStaffInformation',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            StaffManagement__pb2.StaffDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeTodaysSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/SeeTodaysSchedule',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            StaffManagement__pb2.StaffSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeTomorrowsSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/SeeTomorrowsSchedule',
            StaffManagement__pb2.StaffDTO.SerializeToString,
            StaffManagement__pb2.StaffSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeeScheduleRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/SeeScheduleRange',
            StaffManagement__pb2.StaffShift.SerializeToString,
            StaffManagement__pb2.StaffSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStaffInRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StaffManagement/GetStaffInRoom',
            Common__pb2.RoomRequest.SerializeToString,
            StaffManagement__pb2.StaffList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
