# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/common/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/absl/abslConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/absl/abslConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/absl/abslTargets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/absl/abslTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCPluginTargets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCPluginTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCTargets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/grpc/gRPCTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-config-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-generate.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-options.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-targets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/protobuf/protobuf-targets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/utf8_range/utf8_range-config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/utf8_range/utf8_range-targets-noconfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/external/grpc/local/lib/cmake/utf8_range/utf8_range-targets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/FrontEnd/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/PatientManagement/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/ResourceManagement/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/RoomManagement/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/Scheduler/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/services/StaffManagement/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/4.2.3/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/4.2.3/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CMakeCXXLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CMakeCommonLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Linker/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Linker/AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Linker/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/Linker/Apple-AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/bin/cmake -P /Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/VerifyGlobs.cmake

/Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/matthewhvizdos/Desktop/COE892/Hospital_Management -B/Users/matthewhvizdos/Desktop/COE892/Hospital_Management/xcode-build
